@echo off
REM Template run.cmd — this file is generated by setup-project.js into target projects
SET SCRIPT_DIR=%~dp0
SET CONFIG_PATH=%SCRIPT_DIR%.kiro\config.json
IF NOT EXIST "%CONFIG_PATH%" (
  echo Missing configuration file: %CONFIG_PATH%
  exit /b 2
)
for /f "delims=" %%i in ('node -e "const c=require('./.kiro/config.json'); console.log(c.executorPath)"') do set EXEC_PATH=%%i
IF NOT DEFINED EXEC_PATH (
  echo Failed to determine executor path from config.json
  exit /b 3
)
node "%EXEC_PATH%" --workspace "%SCRIPT_DIR%" %*