name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Check for outdated dependencies
      id: outdated
      run: |
        npm outdated --json > outdated.json || true
        if [ -s outdated.json ]; then
          echo "has_updates=true" >> $GITHUB_OUTPUT
        else
          echo "has_updates=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Update dependencies
      if: steps.outdated.outputs.has_updates == 'true'
      run: |
        npm update
        npm audit fix --audit-level=moderate || true
    
    - name: Run tests
      if: steps.outdated.outputs.has_updates == 'true'
      run: |
        npm ci
        npm test
      continue-on-error: true
    
    - name: Create Pull Request
      if: steps.outdated.outputs.has_updates == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes
          - Updated npm dependencies to latest compatible versions
          - Applied security fixes where available
          
          ### Testing
          - [ ] All tests pass
          - [ ] Extension builds successfully
          - [ ] Manual testing completed
          
          Please review the changes and test thoroughly before merging.
        branch: automated-dependency-updates
        delete-branch: true
        labels: dependencies, automated

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
    
    - name: Check for vulnerabilities
      id: audit
      run: |
        AUDIT_RESULT=$(npm audit --json)
        VULNERABILITIES=$(echo $AUDIT_RESULT | jq '.metadata.vulnerabilities.total')
        
        if [ "$VULNERABILITIES" -gt 0 ]; then
          echo "vulnerabilities=$VULNERABILITIES" >> $GITHUB_OUTPUT
          echo "⚠️ Found $VULNERABILITIES vulnerabilities"
        else
          echo "vulnerabilities=0" >> $GITHUB_OUTPUT
          echo "✅ No vulnerabilities found"
        fi
    
    - name: Create issue for vulnerabilities
      if: steps.audit.outputs.vulnerabilities != '0'
      uses: actions/github-script@v7
      with:
        script: |
          const vulnerabilities = '${{ steps.audit.outputs.vulnerabilities }}';
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: `Security: ${vulnerabilities} vulnerabilities found in dependencies`,
            body: `## Security Audit Alert
            
            The automated security audit found ${vulnerabilities} vulnerabilities in project dependencies.
            
            ### Action Required
            1. Review the vulnerabilities by running \`npm audit\`
            2. Update affected packages
            3. Test the extension thoroughly
            4. Close this issue once resolved
            
            ### Commands
            \`\`\`bash
            npm audit
            npm audit fix
            \`\`\`
            `,
            labels: ['security', 'dependencies', 'automated']
          });
