name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Run registry & integration tests
        run: |
          node scripts/tests/test-registry-cli.js
          node scripts/tests/test-registry-concurrency.js
          node scripts/tests/integration-dryrun.js
      - name: Upload test artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: scripts/tests/ci-artifacts/**
          if-no-files-found: warn

  tests-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install deps
        run: npm ci
      - name: Run registry & integration tests
        shell: powershell
        run: |
          node scripts/tests/test-registry-cli.js
          node scripts/tests/test-registry-concurrency.js
          node scripts/tests/integration-dryrun.js
      - name: Upload test artifacts (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: scripts/tests/ci-artifacts/**
          if-no-files-found: warn
